Fix binpac patch spec
Without python-rpm-macros installed I was receiving a macro error when building on Centos 7

Fix RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/lib64/bro/plugins/Bro_AF_Packet/broctl/af_packet.pyc
   /usr/lib64/bro/plugins/Bro_AF_Packet/broctl/af_packet.pyo

libmaxminddb0 is the name of the package built in this repository, not libmaxminddb. Updating accordingly

Rename pkg-config to pkgconfig

This was causing my builds to error, it seems pkgconfig works both on CentOS and RHEL

Add bro-aux as a dependency of bro